### ISSUE TITLE
Add Small Slideshow to Home below about us

### ISSUE THREAD

**Issue by ccsouthard** [slang800/jkniselylandscaping.com#2]
Add JS slideshow. Small gallery read with categories: custom hardscapes and property management.
- JS Plugin: https://owlcarousel2.github.io/OwlCarousel2/
## Categories
 - stonework
 - property maintenance 
(edited for correct ratios below)

**Comment by notslang** [comment]
It doesn't look like any of the photos in the custom stonework directory have been cropped to the correct aspect ratio.

**Comment by ccsouthard** [comment]
Please find the attached folder of photos with correct aspect ratio. https://www.dropbox.com/sh/8lmh7m0u93cf6x4/AAA5XfelqYa8vM4LAy6cM5w_a?dl=0
All gallery photos are (1080 x 810). Hero image file names can be used as captions.
